version: '3.7'

networks:
  backend:
  # Use a backend service comunicate with 
    driver: bridge
  frontend:
    # Use a front end comunicate with gateway
    driver: bridge


services:

  walletservice:
    build: 
      context: ./wallet
      dockerfile: Dockerfile
      
    ports:
      - 9090:9090
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@localhost:27017/
    depends_on:
      - mongodb_container
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  authservice:
    build: 
      context: ./userinfo
      dockerfile: Dockerfile
      
    ports:
      - 9091:9091
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@localhost:27017/
    depends_on:
      - mongodb_container
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateservice:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
      
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb_container
  
    
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ui:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.UI
      context: ./UI2
    volumes:
      - /app/node_modules
      - ./UI2:/app
    networks:
      - frontend
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  mongodb_data_container: