# FROM node:alpine
# WORKDIR /app
# COPY package.json ./
# COPY package-lock.json ./
# COPY ./ ./
# COPY --chown=node:node package.json .
# RUN chmod 777 /app/node_modules
# RUN npm i
# COPY --chown=node:node . .
# USER node
# CMD ["npm", "run", "start"]

FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]